package edu.gatech.hava.engine;

import edu.gatech.hava.engine.exception.IncompleteHavaException;

/**
 * A native (Java) iterator that may be invoked from Hava source. Several
 * iterators are predefined in Hava, and others may be registered with the Engine.
 * An external registered iterator must implement this interface.
 */
public interface HIterator {

    /**
     * Performs the calculations associated with a particular HIterator.
     */
    public interface HIteratorInstance {

        /**
         * Submits an index-value pair to the iterator.
         *
         * @param index If the directive is chained, the index can be null.
         */
        void addCase(HValue index,
                     HValue value)
            throws IncompleteHavaException;

        /**
         * @return true if the value of this iterator is fully determined
         *         from the cases already submitted. For example, the iterator
         *         first returns true after the first case has been submitted.
         */
        boolean isComplete();

        /**
         * @return the value generated by this iterator.
         */
        HValue getValue();

    }

    /**
     * @return the name of this function as it would appear in a Hava
     *         invocation, for example, "median".
     */
    String getIdentifier();

    /**
     * @return true if this iterator uses an index value (for example, argmax or argmin).
     *         In this case, chained directives are not permitted.
     */
    boolean requiresIndex();

    /**
     * @return a fresh instance of this iterator.
     */
    HIteratorInstance createInstance();

}
